### PR TITLE
option to passthru stdout/stderr to controlling tty

### PR DESCRIPTION
**Pull request by asobrien**
See [PagerDuty/cronner PR #49](https://github.com/PagerDuty/cronner/pull/49)

### CODE REVIEW

**Comment by asobrien** [comment]
@theckman This PR adds an additional commit to fix merge conflicts against master on this fork and bumps the version number to `0.3.2` to reflect the updates published in this fork.

Once again, thanks for maintaining this project!

**Comment by asobrien** [comment]
I bumped the version to `0.4.0` to match the semver spec.

**Comment by theckman** [comment]
@asobrien I really appreciate you taking the time to clean up and duplicate the PR on to this repo. I'm going to merge this and cut the release shortly afterwards.

**Comment by theckman** [comment]
Here's the release: https://github.com/theckman/cronner/releases/tag/v0.4.0

**Pull request merged**
